language: go
sudo: false
go:
- 1.11.x

stages:
  - test
  - name: deploy 
    if: branch = master 

jobs:
  include:
  - stage: test
    install: true
    script:
    - echo "tests here"
    #- go test ./... -coverprofile=coverage.out -covermode=atomic -p=1
    #after_success:
    #- bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    services: docker
    install: true
    script:
    - docker run -it
      -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN
      -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG
      -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger 

notifications:
  email: false
  slack:
    secure: jyrXLz+u9WEKYyCL9ZbPxqkw2U2oYTd6ZriGSyZ31v6/deKdG62fQpxHVFeJ6ytvPk5E77OJAhJhaNHTbB42ogocny9MaN6gR073CM7ch1Su7MF9ZX6fOA6KhaAmZE8W+EP7H1MP95eWis6V9jSe1d8uyjktbUXoex5isjuwRunHfvEZqTgd+GWfEDrbvaGetw1LGfpbg2cRTpqOSv8tlJUNOjXMw+IAymPLqElkseiwEFB0RXVq6alNebGrxsmDUP2WS+363wp19cpOffBIDshvpi8yDYJbsQptNaJk2IKFlzZNzATaPpJ9ThMJgNK6vTxSZXoh/SzGdXDfGkUze+hlPsZDKbIMfe4bpVJ1e/AcOI5z1V3VRpgLXxQmLXq3WJZitZA/Nm9MtVv1oYnl2n4q5J4Ep7GUdLKKi2SlnSulhZa6NklEG03bqGKpiQ+spXxt0CUgQ1AlPU51m+pgGveCbgVl/mMzXjkJ5uoYMf/wNd+YGIC611XOxiH6tGBUoyWLxuPsLomD9eWZtjwHfe/hlFsiwxjVdQ6SXCl6x9MN2Idr973vgaCtH1d0HLe6T3KmlrYwWRONxHsyClIVEi3VtdXbKoaQ86SD59bXm8HTWWopNs81/3jqRi5YR4asgi7fb5hRNmmhVbln2b7WeWbTSN5Tz7LrnyJ7ECKlJzg=
