version: '3.6'

services:
  paysuper-webhook-notifier:
    build: .
    container_name: paysuper-webhook-notifier
    networks:
      - p1devnet
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - centrifugo
    ports:
      - "8087:8087"
    tty: true
    environment:
      BROKER_ADDRESS: "amqp://rabbitmq:5672"
      CENTRIFUGO_URL: "centrifugo:8000"
      CENTRIFUGO_KEY: "api_secret"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      name: "rabbitmq"
    networks:
      - p1devnet
      
  consul:
    image: consul:latest
    command: consul agent -dev -client 0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      
  centrifugo:
    image: centrifugo/centrifugo:latest
    environment:
        - CENTRIFUGO_SECRET=secret
        - CENTRIFUGO_ADMIN_PASSWORD=admin
        - CENTRIFUGO_ADMIN_SECRET=secret
    volumes:
        - D:/Projects/Go/github.com/ProtocolONE/payone-notifier/configs/centrifugo:/centrifugo
    tty: true
    command: centrifugo --admin -c /centrifugo/config.json
    ports:
      - "8000:8000"
    networks:
        - p1devnet
              
networks:
  p1devnet:
    external: true