// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/grpc.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckUserRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	SecretKey            string   `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *CheckUserRequest) Reset()         { *m = CheckUserRequest{} }
func (m *CheckUserRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUserRequest) ProtoMessage()    {}
func (*CheckUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{0}
}

func (m *CheckUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserRequest.Unmarshal(m, b)
}
func (m *CheckUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserRequest.Marshal(b, m, deterministic)
}
func (m *CheckUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserRequest.Merge(m, src)
}
func (m *CheckUserRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUserRequest.Size(m)
}
func (m *CheckUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserRequest proto.InternalMessageInfo

func (m *CheckUserRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CheckUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CheckUserRequest) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

type CheckUserResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *CheckUserResponse) Reset()         { *m = CheckUserResponse{} }
func (m *CheckUserResponse) String() string { return proto.CompactTextString(m) }
func (*CheckUserResponse) ProtoMessage()    {}
func (*CheckUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{1}
}

func (m *CheckUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserResponse.Unmarshal(m, b)
}
func (m *CheckUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserResponse.Marshal(b, m, deterministic)
}
func (m *CheckUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserResponse.Merge(m, src)
}
func (m *CheckUserResponse) XXX_Size() int {
	return xxx_messageInfo_CheckUserResponse.Size(m)
}
func (m *CheckUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserResponse proto.InternalMessageInfo

func (m *CheckUserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CheckUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type User struct {
	// @inject_tag: json:"project_account"
	ProjectAccount string `protobuf:"bytes,1,opt,name=project_account,json=projectAccount,proto3" json:"project_account"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`
	// @inject_tag: json:"phone"
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone"`
	// @inject_tag: json:"metadata"
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_unrecognized     []byte            `json:"-" bson:"-" structure:"-" validate:"-"`
	XXX_sizecache        int32             `json:"-" bson:"-" structure:"-" validate:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_81ea47a3f88c2082, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetProjectAccount() string {
	if m != nil {
		return m.ProjectAccount
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*CheckUserRequest)(nil), "grpc.CheckUserRequest")
	proto.RegisterType((*CheckUserResponse)(nil), "grpc.CheckUserResponse")
	proto.RegisterType((*User)(nil), "grpc.User")
	proto.RegisterMapType((map[string]string)(nil), "grpc.User.MetadataEntry")
}

func init() { proto.RegisterFile("grpc/grpc.proto", fileDescriptor_81ea47a3f88c2082) }

var fileDescriptor_81ea47a3f88c2082 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x35, 0x6d, 0x5a, 0xcd, 0x2d, 0xda, 0x3a, 0x48, 0x0d, 0x05, 0xa5, 0xe4, 0xc5, 0xbe, 0x34,
	0x81, 0xea, 0x83, 0xa8, 0x14, 0x54, 0xfa, 0x24, 0x0a, 0x46, 0x7c, 0xd9, 0x97, 0x32, 0x9d, 0xbd,
	0x9b, 0x64, 0xd3, 0x64, 0x66, 0xe7, 0xa3, 0x4b, 0xfe, 0xee, 0xfe, 0x92, 0x65, 0x26, 0x69, 0xf7,
	0xeb, 0x25, 0x9c, 0x73, 0x26, 0x73, 0xcf, 0xc9, 0xc9, 0x85, 0x71, 0x26, 0x05, 0x4b, 0xec, 0x23,
	0x16, 0x92, 0x6b, 0x4e, 0x7c, 0x8b, 0x23, 0x06, 0x93, 0x9f, 0x39, 0xb2, 0xf2, 0xbf, 0x42, 0x99,
	0xe2, 0x95, 0x41, 0xa5, 0xc9, 0x04, 0xfa, 0x46, 0xee, 0x43, 0x6f, 0xee, 0x2d, 0x82, 0xd4, 0x42,
	0xf2, 0x1e, 0x7c, 0xa3, 0x50, 0x86, 0xbd, 0xb9, 0xb7, 0x18, 0xad, 0x20, 0x76, 0x63, 0xdc, 0x15,
	0xa7, 0x93, 0x77, 0x00, 0x0a, 0x99, 0x44, 0xbd, 0x2d, 0xb1, 0x09, 0xfb, 0xee, 0x62, 0xd0, 0x2a,
	0xbf, 0xb0, 0x89, 0x36, 0xf0, 0xfa, 0x9e, 0x89, 0x12, 0xbc, 0x56, 0x48, 0xa6, 0x30, 0x54, 0x9a,
	0x6a, 0xa3, 0x9c, 0xd1, 0x20, 0xed, 0x18, 0x09, 0xe1, 0x79, 0x85, 0x4a, 0xd1, 0x0c, 0x9d, 0x5d,
	0x90, 0x1e, 0x69, 0x74, 0xe3, 0x81, 0x6f, 0x47, 0x90, 0x0f, 0x30, 0x16, 0x92, 0x5f, 0x22, 0xd3,
	0x5b, 0xca, 0x18, 0x37, 0xb5, 0xee, 0xc2, 0xbe, 0xea, 0xe4, 0xef, 0xad, 0x4a, 0x08, 0xf8, 0x35,
	0xad, 0x8e, 0x83, 0x1c, 0x26, 0x6f, 0x60, 0x80, 0x15, 0x2d, 0xf6, 0x5d, 0xcc, 0x96, 0x58, 0x55,
	0xe4, 0xbc, 0xc6, 0xd0, 0x6f, 0x55, 0x47, 0xc8, 0x27, 0x78, 0x51, 0xa1, 0xa6, 0xe7, 0x54, 0xd3,
	0x70, 0x30, 0xef, 0x2f, 0x46, 0xab, 0xf0, 0xee, 0xdb, 0xe3, 0xdf, 0xdd, 0xd1, 0xa6, 0xd6, 0xb2,
	0x49, 0x4f, 0x6f, 0xce, 0xbe, 0xc2, 0xcb, 0x07, 0x47, 0xb6, 0x50, 0xdb, 0x4b, 0x57, 0x68, 0x89,
	0x8d, 0xb5, 0x3b, 0xd0, 0xbd, 0x39, 0x26, 0x6b, 0xc9, 0x97, 0xde, 0x67, 0x6f, 0xf5, 0x17, 0xc6,
	0x7f, 0xb8, 0x2e, 0x2e, 0x0a, 0x94, 0xff, 0x50, 0x1e, 0x0a, 0x86, 0x64, 0x0d, 0xc1, 0xa9, 0x3e,
	0x32, 0x6d, 0x03, 0x3c, 0xfe, 0x69, 0xb3, 0xb7, 0x4f, 0xf4, 0xb6, 0xe7, 0xe8, 0xd9, 0x8f, 0xf5,
	0xd9, 0xb7, 0xac, 0xd0, 0xb9, 0xd9, 0xc5, 0x8c, 0x57, 0x89, 0xa0, 0x8d, 0x32, 0x02, 0xe5, 0x09,
	0x2c, 0xaf, 0x71, 0x97, 0x73, 0x5e, 0x2e, 0xeb, 0xce, 0x37, 0x11, 0x65, 0x96, 0xb8, 0x25, 0x71,
	0xfb, 0xb2, 0x1b, 0x3a, 0xfc, 0xf1, 0x36, 0x00, 0x00, 0xff, 0xff, 0x94, 0xe2, 0x14, 0xfa, 0x43,
	0x02, 0x00, 0x00,
}
